config/routes.rb
Rails.application.routes.draw do
  
  get 'users/new'

  root          'static_pages#home'
  get 'articles' => 'static_pages#articles'
  get 'types' => 'static_pages#types'
  get 'ebooks' =>   'static_pages#ebooks'
  get 'intp' => 'static_pages#intp'
  get 'entp' => 'static_pages#entp'
  get 'enfp' => 'static_pages#enfp'
  get 'infp' => 'static_pages#infp'
  get 'entj' => 'static_pages#entj'
  get 'intj' => 'static_pages#intj'
  get 'enfj' => 'static_pages#enfj'
  get 'infj' => 'static_pages#infj'
  get 'estp' => 'static_pages#estp'
  get 'istp' => 'static_pages#istp'
  get 'esfp' => 'static_pages#esfp'
  get 'isfp' => 'static_pages#isfp'
  get 'estj' => 'static_pages#estj'
  get 'istj' => 'static_pages#istj'
  get 'esfj' => 'static_pages#esfj'
  get 'isfj' => 'static_pages#isfj'
 

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

def hello
	render text: "hello, world!"
end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def info
  end

  def types
  end

  def articles
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

# Returns the full title on a per-page basis.
def full_title(page_title = '')
	base_title = "Personality Preferences"
	if page_title.empty?
		base_title
	else
		"#{page_title} | #{base_title}"
	end
end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
<nav>
	<ul>
		<li><%= link_to "More Info" , '#' %></li>
		<li><%= link_to "Ebooks", ebooks_path %></li>
	</ul>
</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Personality Preferences", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "16 Types", types_path %></li>
        <li><%= link_to "Articles", articles_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title><%= full_title(yield(:title)) %></title>
	  <%= stylesheet_link_tag    "application", media: "all", 
  											"data-turbolinks-track" => true %>
  
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
	<%= render 'layouts/header' %> 
		<div class="container">
			<%= yield %>
			<%= render 'layouts/footer' %>
			
		</div>
	</body>
	
</html>

app/views/static_pages/ebooks.html.erb
<% provide(:title, "Ebooks") %>

app/views/static_pages/entp.html.erb
<h1>
	ENTP
</h1>
<h2>
	The Originator
</h2>
<p>The ENTP's are known for their original somewhat eccentric ideas. They have the ability to spot undelying trends 
and patterns (Ne) which are seemingly unrecognisable for the majority of ohter people. </p>


<p>To have a further in depth look at the ENTP Personality type. Please view my book <%= link_to "ENTP Manual", ebooks_path %></td>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
	<h1>Welcome to Personality Preferences</h1>

	<h2>
		Home of the 16 personality types
	</h2>

	<p>Do you wish to find out more about your personality and those around you?<br>
		Bored of reading the same descriptions?<br>
		Do you wish to gain a in depth understanding of human psychology?<br>
		Do you want to know more about the myers briggs theory?</br>
	</p>



	<%= link_to "Explore Types!", types_path , class: "btn btn-lg btn-primary" %>

</div>

app/views/static_pages/intp.html.erb
<h1>
	INTP
</h1>
<h2>
	The Thinker
</h1>

app/views/static_pages/types.html.erb
<% provide(:title, "16 Types") %>

<h1>16 Personality Types</h1>

<center>

<table width ="600" cellpadding="10" cellspacing="10">
	
<tr>
	<th width="90"></th>
<th><td><%= link_to "ENTP", entp_path %></td>
<th><td><%= link_to "INTP", intp_path %></td>

<th><td><%= link_to "ENTJ", entj_path %></td>
<th><td><%= link_to "INTJ", intj_path %></td>

</tr>
<tr>
	<th width="90"></th>
<th><td><a style="color:black; text-decoration:none"> 	<%= link_to "ENFP", enfp_path %></td>
<th><td><a style="color:black; text-decoration:none"> 	<%= link_to "INFP", infp_path %></td>

<th><td><a style="color:black; text-decoration:none"> 	<%= link_to "ENFJ", enfj_path %></td>
<th><td><a style="color:black; text-decoration:none"> 	<%= link_to "INFJ", infj_path %></td>
</tr>
<tr>
	<th width="90"></th>
<th><td><a style="color:black; text-decoration:none"> 	<%= link_to "ESTP", estp_path %></td>
<th><td><a style="color:black; text-decoration:none"> 	<%= link_to "ISTP", istp_path %></td>

<th><td><a style="color:black; text-decoration:none"> 	<%= link_to "ESTJ", estj_path %></td>
<th><td><a style="color:black; text-decoration:none"> 	<%= link_to "ISTJ", istj_path %></td>
</tr>

<tr>
	<th width="90"></th>
<th><td><a style="color:black; text-decoration:none"> 	<%= link_to "ESFP", esfp_path %></td>	
<th><td><a style="color:black; text-decoration:none"> 	<%= link_to "ISFP", estp_path %></td>

<th><td><a style="color:black; text-decoration:none"> 	<%= link_to "ESFJ", estp_path %></td>
<th><td><a style="color:black; text-decoration:none">	<%= link_to "ISFJ", estp_path %></td>
</tr>


</table>
</center>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<p>This will be a signup page for new users. </p>